name       : octave
version    : 4.0.3
release    : 2
source     :
    - ftp://ftp.gnu.org/gnu/octave/octave-4.0.3.tar.xz : dc2bec8c68fa5733a5847563634b1729356a84f3a5071008ecdb793293f0aa85
license    : GPL-2.0
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
description: |
    GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(QtCore)
    - pkgconfig(libcurl)
    - pkgconfig(xft)
    - ghostscript-devel
    - glpk-devel
    - gnuplot
    - gperf
    - openblas-devel
    - suitesparse-devel
setup      : |
    %configure --prefix=/usr --disable-docs
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/octave.desktop $installdir/usr/share/applications/octave.desktop
