name       : octave
version    : 4.4.1
release    : 25
source     :
    - https://ftp.gnu.org/gnu/octave/octave-4.4.1.tar.lz : 1e6e3a72b4fd4b4db73ccb9f3046e4f727201c2e934b77afb04a804d7f7c4d4b
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for numerical computations
description: |
    GNU Octave is a high-level language, primarily intended for numerical computations. It provides a convenient command line interface for solving linear and nonlinear problems numerically, and for performing other numerical experiments using a language that is mostly compatible with Matlab. It may also be used as a batch-oriented language.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(xft)
    - arpack-devel
    - bzip2-devel
    - fltk-devel
    - ghostscript-devel
    - gl2ps-devel
    - glpk-devel
    - gnuplot
    - gperf
    - hdf5-devel
    - icoutils
    - openblas-devel
    - openjdk-8-devel
    - qrupdate-devel
    - qscintilla-devel
    - suitesparse-devel
    - texlive-devel
    - texlive-fonts-extra
setup      : |
    %reconfigure --prefix=/usr --with-qt=5
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
