name       : octave
version    : 4.2.1
release    : 15
source     :
    - https://ftp.gnu.org/gnu/octave/octave-4.2.1.tar.lz : 225d7e775c19abfc9bbc685c3dbe5ca22d2622e83fee34b8f583cb742083f027
license    : GPL-2.0
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for
    numerical computations.
description: |
    GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(xft)
    - arpack-devel
    - bzip2-devel
    - fltk-devel
    - ghostscript-devel
    - gl2ps-devel
    - glpk-devel
    - gnuplot
    - gperf
    - hdf5-devel
    - icoutils
    - openblas-devel
    - openjdk-8-devel
    - qrupdate-devel
    - qscintilla-qt5-devel
    - suitesparse-devel
    - texlive-devel
    - texlive-fonts-extra
setup      : |
    %patch -p1 < $pkgfiles/octave-gnulib.patch
    %reconfigure --prefix=/usr --with-qt=5
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/octave.desktop $installdir/usr/share/applications/octave.desktop
