name       : octave
version    : 5.2.0
release    : 32
source     :
    - https://ftp.gnu.org/gnu/octave/octave-5.2.0.tar.lz : 86ae3ad64380e0727e4e2d696d13e226e15722ece6b22cf94354fd6e0d6e88a0
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for numerical computations
description: |
    GNU Octave is a high-level language, primarily intended for numerical computations. It provides a convenient command line interface for solving linear and nonlinear problems numerically, and for performing other numerical experiments using a language that is mostly compatible with Matlab. It may also be used as a batch-oriented language.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(openblas)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(ptexenc)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sndfile)
    - pkgconfig(xft)
    - arpack-devel
    - bzip2-devel
    - fltk-devel
    - ghostscript-devel
    - gl2ps-devel
    - glpk-devel
    - gnuplot
    - gperf
    - hdf5-devel
    - icoutils
    - openjdk-8-devel
    - qrupdate-devel
    - qscintilla-devel
    - suitesparse-devel
    - texlive-fonts-extra
setup      : |
    %patch -p1 < $pkgfiles/0001-Unset-QPA_PLATFORMTHEME.patch
    %reconfigure --with-qt=5
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
