name       : octave
version    : 4.0.2
release    : 1
source     :
    - ftp://ftp.gnu.org/gnu/octave/octave-4.0.2.tar.xz : 98c11ecead8ea759eb1d010ad6319a63a1c6199d3a7e2abbafe453c753090403
license    : GPL-2.0
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
description: |
    GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(QtCore)
    - pkgconfig(libcurl)
    - pkgconfig(xft)
    - pkgconfig(zlib)
    - glpk-devel
    - openblas-devel
    - suitesparse-devel
setup      : |
    %configure --prefix=/usr --disable-docs
build      : |
    %make
install    : |
    %make_install
