name       : octave
version    : 4.0.3
release    : 7
source     :
    - ftp://ftp.gnu.org/gnu/octave/octave-4.0.3.tar.xz : dc2bec8c68fa5733a5847563634b1729356a84f3a5071008ecdb793293f0aa85
license    : GPL-2.0
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for
    numerical computations.
description: |
    GNU Octave is a high-level interpreted language, primarily intended for numerical computations.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(QtCore)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(sndfile)
    - pkgconfig(xft)
    - fltk-devel
    - ghostscript-devel
    - gl2ps-devel
    - glpk-devel
    - gnuplot
    - gperf
    - hdf5-devel
    - icoutils
    - openblas-devel
    - openjdk-8-devel
    - qscintilla-devel
    - suitesparse-devel
    - texlive-devel
setup      : |
    %patch -p1 < $pkgfiles/gcc6.patch
    find -name \*.cc -o -name \*.h -o -name \*.yy | xargs sed -i -e 's/#include <c\(math\|stdlib\)>/#include <\1.h>/'
    find -name \*.h -o -name \*.cc | xargs sed -i -e 's/<config.h>/"config.h"/' -e 's/<base-list.h>/"base-list.h"/'
    %configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/octave.desktop $installdir/usr/share/applications/octave.desktop
