name       : octave
version    : 8.2.0
release    : 42
source     :
    - https://ftp.gnu.org/gnu/octave/octave-8.2.0.tar.lz : 8ac875a9f8e44b8eb4b75ca8638531e2ca47cd9d13a6ca39d3a0eccd175f8a05
homepage   : https://www.gnu.org/software/octave/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : GNU Octave is a high-level interpreted language, primarily intended for numerical computations
description: |
    GNU Octave is a high-level language, primarily intended for numerical computations. It provides a convenient command line interface for solving linear and nonlinear problems numerically, and for performing other numerical experiments using a language that is mostly compatible with Matlab. It may also be used as a batch-oriented language.
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fontconfig)
    - pkgconfig(glu)
    - pkgconfig(hdf5)
    - pkgconfig(lapack)
    - pkgconfig(lcms2)
    - pkgconfig(libcurl)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(openblas)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(ptexenc)
    - pkgconfig(sndfile)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
    - arpack-devel
    - fltk-devel
    - ghostscript-devel
    - gl2ps-devel
    - glpk-devel
    - gnuplot
    - gperf
    - icoutils
    - openjdk-11-devel
    - qrupdate-devel
    - qscintilla-devel
    - suitesparse-devel
    - texlive-fonts-extra
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11/
setup      : |
    %patch -p1 < $pkgfiles/0001-Unset-QPA_PLATFORMTHEME.patch
    %configure --with-qt=5
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
